version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  node-app:
    #ovo je za docker swarm
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 5s
    build: .
    image: jurejukic/node-docker-node-app:latest
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    env_file:
      - ./.env_mongo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
